(package "helm-themes"
         "0.05"
         "Color theme selection with helm interface")

(website-url "https://github.com/syohex/emacs-helm-themes")
(keywords "")

(package-file "helm-themes.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "24.4")
(depends-on "helm")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
